/* Autogenerated by checkver.pl */
const char lxdream_package_name[] = "mxdream 0.1";
const char lxdream_short_version[] = "0.1";
const char lxdream_full_version[] = "0.1";
const char lxdream_copyright[] = "Copyright (C) 2005-2008 Nathan Keynes";
