#ifndef PVR2_SHADERS_H_DECLS
#define PVR2_SHADERS_H_DECLS
/* Minimal decls for upscaler program (generated by genglsl normally) */
void glsl_use_upscale_simple(void);
void glsl_set_upscale_simple_view_matrix(const float *m4);
void glsl_set_upscale_simple_in_vertex_pointer(const void *ptr, int stride);
void glsl_set_upscale_simple_in_texcoord_pointer(const void *ptr, int stride);
void glsl_set_upscale_simple_primary_texture(int unit);
void glsl_set_upscale_simple_texel_size(const float v2[2]);
void glsl_set_upscale_simple_sharp(float sharp);
#endif
